apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  interval: 5m
  chart:
    spec:
      chart: crossplane
      version: ">=1.15.0"
      sourceRef:
        kind: HelmRepository
        name: crossplane-stable
        namespace: flux-system
  install:
    createNamespace: true