apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: boutique-irsa
  region: us-west-2
  version: "1.27"
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      attachPolicyARNs:
        - arn:aws:iam::123456789012:policy/AWSLoadBalancerControllerIAMPolicy
    - metadata:
        name: cluster-autoscaler
        namespace: kube-system
      attachPolicyARNs:
        - arn:aws:iam::123456789012:policy/ClusterAutoscalerPolicy
managedNodeGroups:
  - name: ng-irsa
    instanceType: m5.large
    minSize: 2
    maxSize: 4
    desiredCapacity: 2
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
