apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: boutique-private-nat
  region: us-west-2
  version: "1.27"
vpc:
  subnets:
    private:
      us-west-2a: { cidr: "10.0.1.0/24" }
      us-west-2b: { cidr: "10.0.2.0/24" }
  nat:
    gateway: Single
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  manageSharedNodeSecurityGroupRules: true
endpoints:
  s3: true
  ecr: true
  sts: true
  dynamodb: false
  ec2: false
  sqs: false
  sns: false
iam:
  withOIDC: true
managedNodeGroups:
  - name: ng-private
    instanceTypes: ["m5.large", "c5.large"]
    minSize: 2
    maxSize: 6
    desiredCapacity: 3
    privateNetworking: true
    subnets:
      - us-west-2a
      - us-west-2b
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
