apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: boutique-ebs-efs
  region: us-west-2
  version: "1.27"
addons:
  - name: aws-ebs-csi-driver
    version: latest
    attachPolicyARN: arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
  - name: aws-efs-csi-driver
    version: latest
managedNodeGroups:
  - name: ng-storage
    instanceType: m5.large
    minSize: 2
    maxSize: 4
    desiredCapacity: 2
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
